name: recipes
description: Recipe Finder

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  logging: ^1.2.0
  auto_size_text: ^3.0.0
  flutter_adaptive_scaffold: ^0.3.1
  desktop_window: ^0.4.0
  path: ^1.9.0
  cached_network_image: ^3.4.1
  flutter_slidable: ^3.1.1
  platform: ^3.1.5
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  chopper: ^8.0.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0
  flutter_html: ^3.0.0-beta.2
  lumberdash: ^3.0.0
  colorize_lumberdash: ^3.0.0
  path_provider: ^2.1.4
  flutter_riverpod: ^2.5.1

  # Database and ORM dependencies
  synchronized: ^3.3.0+2
  sqlbrite: ^2.8.0
  sqlite3_flutter_libs: ^0.5.24
  sqlite3: ^2.4.6
  web_ffi: ^0.7.2
  drift: ^2.20.2

  # Encryption dependencies
  flutter_secure_storage: ^9.2.2

  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/menubar
      ref: 12decbe0f592e14e03223f6f2c0c7e0e2dbd70a1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  chopper_generator: ^8.0.2
  freezed: ^2.5.7
  drift_dev: ^2.20.3
  test_cov_console: ^0.2.2

  flutter_lints: ^4.0.0
  test: ^1.25.7
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/recipe_details.json
    - assets/recipe_details_2.json
    - assets/images/