import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:recipes/data/database/recipe_db.dart';
import 'package:recipes/data/models/ingredient.dart';
import 'package:recipes/data/repositories/db_repository.dart';
import 'package:test/test.dart';

import 'db_repository_test.mocks.dart';

// This will tell mockito to generate mocks for all the classes listed
// in the parameter.
@GenerateNiceMocks([
  MockSpec<RecipeDatabase>(),
  MockSpec<RecipeDao>(),
  MockSpec<IngredientDao>(),
])
void main() {
  // MockRecipeDatabase, MockIngredientDao and MockRecipeDao are
  // generated by mockito using the build runner.

  final mockDb = MockRecipeDatabase();
  final mockIngredientDao = MockIngredientDao();
  final mockRecipeDao = MockRecipeDao();

  final randomIngredients = [
    const Ingredient(
      id: 1123,
      recipeId: 123,
      name: 'Pasta',
      amount: 1.0,
    ),
    const Ingredient(
      id: 1124,
      recipeId: 123,
      name: 'Garlic',
      amount: 1.0,
    ),
    const Ingredient(
      id: 1125,
      recipeId: 123,
      name: 'Breadcrumbs',
      amount: 5.0,
    ),
  ];

  /*
    `when` is a special function provided by mockito that allows me
     to control how a mock should behave.
     It indicates that whenever I try to access mockDb.ingredientDao or
     mockDb.recipeDao, the mocked version should be used.
  */
  when(mockDb.ingredientDao).thenReturn(mockIngredientDao);
  when(mockDb.recipeDao).thenReturn(mockRecipeDao);

  group('DBRepository', () {
    test('can instantiate', () {
      // Arrange
      late DBRepository dbRepository;

      // Act
      dbRepository = DBRepository(
        recipeDatabase: mockDb,
      );

      // Assert
      expect(dbRepository, isNotNull);
      expect(dbRepository.recipeDatabase, isNotNull);
    });

    // Find all ingredients
    test('findIngredients', () async {
      // Arrange
      final dbRepository = DBRepository(
        recipeDatabase: mockDb,
      );
      await dbRepository.init();

      // Mock the findAllIngredients method to return a list of ingredients.
      when(mockIngredientDao.findAllIngredients()).thenAnswer((_) async {
        return randomIngredients
            .map((e) => DbIngredientData(
                id: e.id!,
                recipeId: e.recipeId!,
                name: e.name!,
                amount: e.amount!))
            .toList();
      });

      // Act
      final result = await dbRepository.findAllIngredients();

      // Assert
      verify(mockIngredientDao.findAllIngredients()).called(1);
      expect(result, equals(randomIngredients));
      expect(result, isNotNull);
      expect(result.length, 3);
    });
  });
}
